echo "read src/require.sh..."

source "${src_dir}/platform.sh"
source "${src_dir}/install_bat.sh"
source "${src_dir}/install_binaries.sh"
source "${src_dir}/install_delta.sh"
source "${src_dir}/install_exa.sh"
source "${src_dir}/install_fd.sh"
source "${src_dir}/install_fzf.sh"
source "${src_dir}/install_gitui.sh"
source "${src_dir}/install_ripgrep.sh"
source "${src_dir}/install_starship.sh"
source "${src_dir}/install_zim.sh"
source "${src_dir}/install_zoxide.sh"
source "${src_dir}/install_zsh.sh"
source "${src_dir}/symlink.sh"
